In [1]:
import numpy as np
import pandas as pd

In [3]:
import tensorflow
import keras

In [10]:
from keras.datasets import mnist

In [11]:
(train_images, train_labels),(test_images, test_labels) = mnist.load_data()
print(train_images.shape)
print(train_labels.shape)
print(test_images.shape)
print(test_labels.shape)

11493376/11490434 [==============================] - 57s 5us/step
(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


<h1>Basic MNIST</h1>

In [5]:
from keras import models
from keras import layers

network = keras.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation='softmax'))

In [6]:
network.compile(optimizer='rmsprop',
               loss='categorical_crossentropy',
               metrics=['accuracy'])

In [7]:
train_images=train_images.reshape(60000,28*28)
train_images = train_images.astype('float32')/255

test_images=test_images.reshape(10000,28*28)
test_images = test_images.astype('float32')/255

In [9]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 7s 124us/step - loss: 0.2565 - acc: 0.9257
Epoch 2/5
60000/60000 [==============================] - 6s 107us/step - loss: 0.1042 - acc: 0.9692
Epoch 3/5
60000/60000 [==============================] - 7s 109us/step - loss: 0.0690 - acc: 0.9790
Epoch 4/5
60000/60000 [==============================] - 7s 109us/step - loss: 0.0498 - acc: 0.9852
Epoch 5/5
60000/60000 [==============================] - 7s 111us/step - loss: 0.0380 - acc: 0.9882


In [10]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print("Test accuracy is {0}".format(test_acc))

10000/10000 [==============================] - 1s 68us/step
Test accuracy is 0.9765


<h3>Proper loss parametes </h3>
<p>Binary classification : binary_crossentropy</p>
<p>Multiclass classification : categorical_crossentropy</p>
<p>Regression : mean_squared_error</p>

<h1>IMDB dataset. Binary classification</h1>

In [14]:
from keras.datasets import imdb

In [15]:
(train_data, train_labels),(test_data, test_labels) = imdb.load_data(num_words=10000)

17465344/17464789 [==============================] - 202s 12us/step


In [16]:
train_data.shape

(25000,)

In [ ]:
train_data[0]

In [20]:
train_labels[:3]

array([1, 0, 0], dtype=int64)

The train_data and test_data is an array of reviews. A review consists of a list of word indices.

In [21]:
def vectorize_sequence(sequences, dim=10000):
    results = np.zeros((len(sequences), dim))
    for i, sequence in enumerate(sequences):
        results[i,sequence] = 1
    return results

In [22]:
x_train = vectorize_sequence(train_data)
x_test = vectorize_sequence(test_data)

In [23]:
x_train.shape

(25000, 10000)

In [28]:
x_train[0:100,]

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [38]:
y_train = np.asarray(train_labels).astype('float32')
y_test = np.asarray(test_labels).astype('float32')

In [39]:
y_train.shape

(25000,)

In [34]:
from keras import models, layers
network = keras.Sequential()
network.add(layers.Dense(16, activation='relu',input_shape=(10000,)))
network.add(layers.Dense(16, activation='relu'))
network.add(layers.Dense(1, activation='sigmoid'))  #as we need probability of success from a single node

In [36]:
network.compile(optimizer="rmsprop",
               loss="mse",
               metrics=['accuracy'])

In [40]:
x_val=x_train[:10000]
x_train_partial = x_train[10000:]

y_val=y_train[:10000]
y_train_partial = y_train[10000:]

In [41]:
network.fit(x_train_partial,
           y_train_partial,
           epochs=10,
           batch_size=512,
           validation_data=(x_val, y_val))

Train on 15000 samples, validate on 10000 samples
Epoch 1/10
15000/15000 [==============================] - 4s 239us/step - loss: 0.5084 - acc: 0.7813 - val_loss: 0.3797 - val_acc: 0.8684
Epoch 2/10
15000/15000 [==============================] - 3s 190us/step - loss: 0.3004 - acc: 0.9046 - val_loss: 0.3004 - val_acc: 0.8897
Epoch 3/10
15000/15000 [==============================] - 3s 196us/step - loss: 0.2179 - acc: 0.9285 - val_loss: 0.3086 - val_acc: 0.8710
Epoch 4/10
15000/15000 [==============================] - 3s 212us/step - loss: 0.1751 - acc: 0.9439 - val_loss: 0.2840 - val_acc: 0.8832
Epoch 5/10
15000/15000 [==============================] - 3s 192us/step - loss: 0.1427 - acc: 0.9543 - val_loss: 0.2842 - val_acc: 0.8871
Epoch 6/10
15000/15000 [==============================] - 3s 193us/step - loss: 0.1150 - acc: 0.9651 - val_loss: 0.3166 - val_acc: 0.8771
Epoch 7/10
15000/15000 [==============================] - 3s 194us/step - loss: 0.0980 - acc: 0.9707 - val_loss: 0.3127 - 

In [42]:
evaluate_test_results = network.evaluate(x_test, y_test)

25000/25000 [==============================] - 4s 148us/step


In [43]:
loss, accuracy = evaluate_test_results
#first one is loss and secodn one is accuracy on test set

[0.41986478815078737, 0.86468]

Thus we have attained an accuracy of 88% on the test set. We can use the predict method on x_test to get probability predictions. Whoopee!!

<h1>IMDB dataset. Multiclass classification</h1>

In [4]:
from keras.datasets import reuters

In [29]:
(train_data, train_labels),(test_data, test_labels) = reuters.load_data(num_words=10000)

In [12]:
train_data.shape

(8982,)

In [ ]:
train_data[0]

In [30]:
x_train = vectorize_sequence(train_data)
x_test = vectorize_sequence(test_data)

In [34]:
def to_one_hot(labels, dim=46):
    results = np.zeros((len(labels),dim))
    for i, label in enumerate(labels):
        results[i,label]=1
    return results

In [35]:
one_hot_train_labels = to_one_hot(train_labels)
one_hot_test_labels = to_one_hot(test_labels)

In [36]:
one_hot_test_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Why choose 64 input nodes? Since the dimesnionality space is much higher here

In [37]:
from keras import models
from keras import layers

In [43]:
network = models.Sequential()
network.add(layers.Dense(64, activation='relu', input_shape=(10000,)))
network.add(layers.Dense(64, activation='relu'))
network.add(layers.Dense(46, activation='softmax'))

In [44]:
network.compile(optimizer='rmsprop',
               loss='categorical_crossentropy',
               metrics=['accuracy'])

In [45]:
x_val=x_train[:1000]
x_train_partial = x_train[1000:]

y_val=one_hot_train_labels[:1000]
y_train_partial = one_hot_train_labels[1000:]


In [46]:
network.fit(x_train_partial,
           y_train_partial,
           epochs=20,
           batch_size=512,
           validation_data=(x_val, y_val))

Train on 7982 samples, validate on 1000 samples
Epoch 1/20
7982/7982 [==============================] - 5s 593us/step - loss: 2.5322 - acc: 0.4955 - val_loss: 1.7208 - val_acc: 0.6120
Epoch 2/20
7982/7982 [==============================] - 3s 348us/step - loss: 1.4452 - acc: 0.6879 - val_loss: 1.3459 - val_acc: 0.7060
Epoch 3/20
7982/7982 [==============================] - 3s 336us/step - loss: 1.0953 - acc: 0.7651 - val_loss: 1.1708 - val_acc: 0.7430
Epoch 4/20
7982/7982 [==============================] - 3s 339us/step - loss: 0.8697 - acc: 0.8165 - val_loss: 1.0793 - val_acc: 0.7590
Epoch 5/20
7982/7982 [==============================] - 3s 371us/step - loss: 0.7034 - acc: 0.8472 - val_loss: 0.9844 - val_acc: 0.7810
Epoch 6/20
7982/7982 [==============================] - 3s 366us/step - loss: 0.5667 - acc: 0.8802 - val_loss: 0.9411 - val_acc: 0.8040
Epoch 7/20
7982/7982 [==============================] - 3s 367us/step - loss: 0.4581 - acc: 0.9048 - val_loss: 0.9083 - val_acc: 0.8020


In [47]:
evaluation = network.evaluate(x_test, one_hot_test_labels)

2246/2246 [==============================] - 1s 297us/step


In [48]:
print(evaluation)

[1.2105563251651619, 0.778717720444884]
